[[redirects]]
  from="/api/*"
  to="https://split-check-vhbp.vercel.app/:splat" 
  status=200
    
[[redirects]]
   from ="/*"
   to ="/index.html"
   status=200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"