[[redirects]]
  from="/api/*"
  to="http://localhost:8000/:splat" 
  status=200
    
[[redirects]]
   from ="/*"
   to ="/index.html"
   status=200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"